<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'CmsTag\Controller\AdminController'   => __DIR__ . '/src/Controller/AdminController.php',
    'CmsTag\Mapping\TaggableInterface'    => __DIR__ . '/src/Mapping/TaggableInterface.php',
    'CmsTag\Mapping\TagInterface'         => __DIR__ . '/src/Mapping/TagInterface.php',
    'CmsTag\Mapping\Traits\TaggableTrait' => __DIR__ . '/src/Mapping/Traits/TaggableTrait.php',
    'CmsTag\Module'                       => __DIR__ . '/src/Module.php',
    'CmsTagTest\Framework\TestCase'       => __DIR__ . '/tests/Framework/TestCase.php',
    'CmsTagTest\SampleTest'               => __DIR__ . '/tests/SampleTest.php',
);
